# Generated by Django 4.1.13 on 2024-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hexauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
